---
- name: Installing NFS Client Packages
  apt:
    name:
      - nfs-common
    state: present

- name: Mounting NFS exports
  mount:
    fstype: "{{ item['fstype'] | default('nfs') }}"
    opts: "{{ item['opts'] | default(omit) }}"
    path: "{{ item['path'] }}"
    src: "{{ item['src'] }}"
    state: "{{ item['state'] |default('mounted') }}"
  become: true
  with_items: '{{ nfs_mounts }}'
  when: nfs_mounts is defined